# Generated by Django 4.2.4 on 2024-05-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=255)),
                ('objet', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
    ]
